// Playwright CLI run-code against the isolated API fixture, never production.
async (page) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const assert = (condition, message) => { if (!condition) throw new Error(message); };
  await page.setViewportSize({width:1280,height:900});
  await page.getByRole('button',{name:'음악 추가',exact:true}).click();
  await page.getByRole('link',{name:'디스코드로 로그인'}).waitFor();
  assert(await page.getByLabel('유튜브 영상 링크').count() === 1, 'Input missing');
  assert(!(await page.getByLabel('유튜브 영상 링크').isVisible()), 'Guest can use form');
  await page.getByRole('button',{name:'음악 추가 닫기'}).click();
  await page.getByRole('button',{name:'재생',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#audio').paused);
  await page.goto('http://127.0.0.1:4533/__login');
  await page.getByLabel('유튜브 영상 링크').waitFor();
  await page.getByRole('button',{name:'음악 추가 닫기'}).click();
  await page.getByRole('button',{name:'재생',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#audio').paused);
  await page.evaluate(()=>{window.__originalAudio=document.querySelector('#audio');window.__originalSource=window.__originalAudio.src;});
  await page.getByRole('button',{name:'음악 추가',exact:true}).click();
  await page.getByLabel('유튜브 영상 링크').fill('https://localhost/private');
  await page.getByRole('button',{name:'ETC에 추가',exact:true}).click();
  await page.getByText('재생목록 대신 유튜브 영상 한 곡의 링크를 입력해 주세요.',{exact:true}).waitFor();
  await page.getByLabel('유튜브 영상 링크').fill('https://youtu.be/jNQXAC9IVRw?list=ignored');
  await page.getByRole('button',{name:'ETC에 추가',exact:true}).click();
  await page.getByText('ETC에 추가됨',{exact:true}).waitFor({timeout:15000});
  assert(await page.evaluate(()=>window.__originalAudio===document.querySelector('#audio') && window.__originalAudio.src===window.__originalSource && !window.__originalAudio.paused),'Import interrupted playing audio');
  assert(await page.locator('.music-add-jobs strong').first().textContent()==='검증용 음악 <script>','Title was not rendered as inert text');
  assert(await page.locator('.album-card').filter({has:page.getByRole('checkbox',{name:'ETC',exact:true})}).locator('.album-count').textContent()==='7곡','ETC count not updated');
  await page.screenshot({path:'output/playwright/music-import/desktop-ready.png'});
  await page.getByRole('button',{name:'듣기',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#audio').src.includes('yt-jNQXAC9IVRw.mp3')&&!document.querySelector('#audio').paused);
  await page.getByRole('button',{name:'음악 추가',exact:true}).click();
  await page.getByLabel('유튜브 영상 링크').fill('https://youtu.be/jNQXAC9IVRw');
  await page.getByRole('button',{name:'ETC에 추가',exact:true}).click();
  await page.getByText('이미 ETC에 있는 곡입니다. 바로 들을 수 있습니다.',{exact:true}).waitFor();
  assert(await page.locator('.music-add-jobs li').count()===1,'Duplicate created another job');
  await page.getByLabel('유튜브 영상 링크').fill('https://youtu.be/FailVideo01');
  await page.getByRole('button',{name:'ETC에 추가',exact:true}).click();
  await page.getByText('영상을 가져오지 못했습니다. 공개 영상인지 확인해 주세요.',{exact:true}).waitFor({timeout:15000});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'output/playwright/music-import/mobile-ready.png'});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile horizontal overflow');
  await page.getByRole('button',{name:'로그아웃',exact:true}).click();
  await page.getByRole('link',{name:'디스코드로 로그인'}).waitFor();
  const response=await page.request.get('http://127.0.0.1:4533/api/imports');
  assert(response.status()===401,'Logout did not revoke session');
  await page.getByRole('button',{name:'음악 추가 닫기'}).click();
  await page.reload();
  await page.getByRole('button',{name:'전체 해제',exact:true}).click();
  await page.getByRole('checkbox',{name:'ETC',exact:true}).check();
  await page.locator('#ulist li').filter({hasText:'검증용 음악 <script>'}).click();
  await page.waitForFunction(()=>document.querySelector('#audio').src.includes('yt-jNQXAC9IVRw.mp3')&&!document.querySelector('#audio').paused);
  assert(!errors.length,'Browser errors: '+errors.join('; '));
  return {guestPlayback:true,authForm:true,invalidURLRejected:true,completedTrackPlayable:true,noPlaybackInterruption:true,duplicateCoalesced:true,failureShown:true,mobileLayout:true,logoutRevoked:true,anonymousAddedTrackPlayback:true,errors};
}
